# Generated by Django 5.1.2 on 2024-10-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255),
            preserve_default=False,
        ),
    ]
