# Generated by Django 5.1.1 on 2024-10-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255, unique=True)),
                ('positive_count', models.IntegerField()),
                ('negative_count', models.IntegerField()),
                ('neutral_count', models.IntegerField()),
                ('gen_description', models.TextField()),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
